import type { DefaultTheme } from 'vitepress'

export const basicSidebar: DefaultTheme.SidebarItem[] = [
  {
    text: 'HTML',
    collapsed: false,
    items: [
      { text: 'contenteditable', link: 'HTML/contenteditable' },
      {
        text: 'SVG',
        collapsed: true,
        items: [
          { text: '概览', link: 'HTML/SVG/概览' },
          { text: '几种元素含义', link: 'HTML/SVG/几种元素含义' },
          { text: 'fill、stroke', link: 'HTML/SVG/fill、stroke' },
          { text: 'SVG 雪碧图', link: 'HTML/SVG/SVG 雪碧图' },
          { text: 'viewbox', link: 'HTML/SVG/viewbox' },
        ],
      },
      { text: '使用 Preload、Prefetch 优化前端页面的资源加载', link: 'HTML/使用 Preload、Prefetch 优化前端页面的资源加载' },
      { text: '字符实体', link: 'HTML/字符实体' },
      { text: '拖放', link: 'HTML/拖放' },
    ],
  },
  {
    text: 'CSS',
    collapsed: true,
    items: [
      { text: 'currentColor', link: 'CSS/currentColor' },
      { text: 'filter', link: 'CSS/filter' },
      {
        text: 'flex',
        collapsed: true,
        items: [
          { text: '概览', link: 'CSS/flex/概览' },
          { text: 'flex-basis', link: 'CSS/flex/flex-basis' },
          { text: 'flex-wrap、flex-shrink', link: 'CSS/flex/flex-wrap、flex-shrink' },
          { text: 'flex 属性值简写', link: 'CSS/flex/flex 属性值简写' },
        ],
      },
      { text: '修改滚动条样式', link: 'CSS/修改滚动条样式' },
      { text: '背景', link: 'CSS/背景' },
    ],
  },
  {
    text: 'JS',
    collapsed: true,
    items: [
      {
        text: 'Blob',
        collapsed: true,
        items: [
          { text: 'arraybuffer', link: 'JS/Blob/arraybuffer' },
          { text: 'Blob URL 和 Data URL 的区别', link: 'JS/Blob/Blob URL 和 Data URL 的区别' },
          { text: '通过接口下载文件', link: 'JS/Blob/通过接口下载文件' },
          { text: 'FormData', link: 'JS/Blob/FormData' },
          { text: '使用文件', link: 'JS/Blob/使用文件' },
        ],
      },
      { text: 'break、continue', link: 'JS/break、continue' },
      { text: 'call、apply、bind', link: 'JS/call、apply、bind' },
      { text: 'decodeURI、decodeURIComponent', link: 'JS/decodeURI、decodeURIComponent' },
      { text: 'ECMAScript', link: 'JS/ECMAScript' },
      { text: 'for 循环', link: 'JS/for 循环' },
      {
        text: 'HTTP',
        collapsed: true,
        items: [
          { text: 'Content-Type', link: 'JS/HTTP/Content-Type' },
          { text: 'OPTIONS 请求方法', link: 'JS/HTTP/OPTIONS 请求方法' },
          { text: '传统项目解决跨域问题', link: 'JS/HTTP/传统项目解决跨域问题' },
          { text: '浏览器缓存机制', link: 'JS/HTTP/浏览器缓存机制' },
        ],
      },
      { text: 'JSON.stringify', link: 'JS/JSON.stringify' },
      { text: 'Math', link: 'JS/Math' },
      { text: 'mouseover、mouseenter', link: 'JS/mouseover、mouseenter' },
      { text: 'Number、parseInt、parseFloat', link: 'JS/Number、parseInt、parseFloat' },
      { text: 'Object.keys', link: 'JS/Object.keys' },
      { text: 'UrlEncode 编码', link: 'JS/UrlEncode 编码' },
      {
        text: '下载',
        collapsed: true,
        items: [
          { text: '概览', link: 'JS/下载/概览' },
        ],
      },
      {
        text: '事件',
        collapsed: true,
        items: [
          { text: '捕获、冒泡', link: 'JS/事件/捕获、冒泡' },
          { text: '事件循环机制', link: 'JS/事件/事件循环机制' },
          { text: '事件调用', link: 'JS/事件/事件调用' },
          { text: 'input、change', link: 'JS/事件/input、change' },
        ],
      },
      {
        text: '位置',
        collapsed: true,
        items: [
          { text: 'pageX、pageY', link: 'JS/位置/pageX、pageY' },
          { text: 'screenX、screenY', link: 'JS/位置/screenX、screenY' },
        ],
      },
      { text: '修改页面内容', link: 'JS/修改页面内容' },
      {
        text: '函数',
        collapsed: true,
        items: [
          { text: '匿名函数', link: 'JS/函数/匿名函数' },
          { text: '立即执行函数', link: 'JS/函数/立即执行函数' },
        ],
      },
      { text: '各种符号', link: 'JS/各种符号' },
      { text: '图片', link: 'JS/图片' },
      {
        text: '尺寸',
        collapsed: true,
        items: [
          { text: 'clientHeight、scrollTop、scrollHeight', link: 'JS/尺寸/clientHeight、scrollTop、scrollHeight' },
          { text: '获取元素宽高', link: 'JS/尺寸/获取元素宽高' },
          { text: 'getBoundingClientRect', link: 'JS/尺寸/getBoundingClientRect' },
          { text: 'js实现文章目录导航', link: 'JS/尺寸/js实现文章目录导航' },
          { text: 'offset', link: 'JS/尺寸/offset' },
        ],
      },
      { text: '换行', link: 'JS/换行' },
      {
        text: '时间',
        collapsed: true,
        items: [
          { text: '日期 Date 兼容性', link: 'JS/时间/日期 Date 兼容性' },
          { text: '日期时间的获取与设置', link: 'JS/时间/日期时间的获取与设置' },
          { text: '时间戳', link: 'JS/时间/时间戳' },
        ],
      },
      {
        text: '模块',
        collapsed: true,
        items: [
          { text: '在 HTML 中使用 ES6 模块语法', link: 'JS/模块/在 HTML 中使用 ES6 模块语法' },
          { text: 'ES6 模块', link: 'JS/模块/ES6 模块' },
          { text: '模块顶级 await', link: 'JS/模块/模块顶级 await' },
        ],
      },
      {
        text: '模块化',
        collapsed: true,
        items: [
          { text: 'AMD', link: 'JS/模块化/AMD' },
          { text: 'CMD', link: 'JS/模块化/CMD' },
          { text: 'CommonJS', link: 'JS/模块化/CommonJS' },
          { text: 'ES6 模块', link: 'JS/模块化/ES6 模块' },
          { text: 'UMD', link: 'JS/模块化/UMD' },
        ],
      },
      {
        text: '正则',
        collapsed: true,
        items: [
          { text: '概览', link: 'JS/正则/概览' },
          { text: 'match', link: 'JS/正则/match' },
          { text: 'replace', link: 'JS/正则/replace' },
        ],
      },
      {
        text: '类',
        collapsed: true,
        items: [
          { text: 'constructor 方法', link: 'JS/类/constructor 方法' },
          { text: 'this 的指向', link: 'JS/类/this 指向' },
        ],
      },
      { text: '类数组', link: 'JS/类数组' },
      { text: '继承与原型链', link: 'JS/继承与原型链' },
      { text: '递归', link: 'JS/递归' },
      { text: '遍历数组删除指定元素', link: 'JS/遍历数组删除指定元素' },
      { text: '闭包', link: 'JS/闭包' },
      { text: '防抖、节流', link: 'JS/防抖、节流' },
    ],
  },
  {
    text: 'NodeJS',
    collapsed: true,
    items: [
      { text: '命令行参数', link: 'NodeJS/命令行参数' },
      { text: 'dirname', link: 'NodeJS/dirname' },
      { text: '环境变量', link: 'NodeJS/环境变量' },
      { text: '使用 Node 实现一个文件上传接口', link: 'NodeJS/使用 Node 实现一个文件上传接口' },
      { text: '模式匹配', link: 'NodeJS/模式匹配' },
      { text: 'nvm', link: 'NodeJS/nvm' },
    ],
  },
  {
    text: 'NPM',
    collapsed: true,
    items: [
      { text: 'npm cli', link: 'NPM/npm cli' },
      { text: 'cli01', link: 'NPM/cli01' },
      { text: 'dependencies-vs-devdependencies', link: 'NPM/dependencies-vs-devdependencies' },
      { text: 'install', link: 'NPM/install' },
      { text: 'install01', link: 'NPM/install01' },
      { text: 'integrity', link: 'NPM/integrity' },
      { text: 'npm-link', link: 'NPM/npm-link' },
      { text: 'npm-mechanism', link: 'NPM/npm-mechanism' },
      { text: 'npx', link: 'NPM/npx' },
      { text: 'nvm-windows', link: 'NPM/nvm-windows' },
      {
        text: 'package',
        collapsed: true,
        items: [
          { text: 'module', link: 'NPM/package/module' },
          { text: 'peerdependencies', link: 'NPM/package/peerdependencies' },
          { text: 'type', link: 'NPM/package/type' },
          { text: 'types', link: 'NPM/package/types' },
          { text: 'unpkg', link: 'NPM/package/unpkg' },
        ],
      },
      { text: 'package-lock', link: 'NPM/package-lock' },
      { text: 'publish-package', link: 'NPM/publish-package' },
      { text: 'scripts-prepend-node-path', link: 'NPM/scripts-prepend-node-path' },
      { text: 'write-package-use-rollup', link: 'NPM/write-package-use-rollup' },
    ],
  },
  {
    text: 'Pnpm',
    collapsed: true,
    items: [
      { text: 'config', link: 'Pnpm/config' },
      { text: 'install', link: 'Pnpm/install' },
      { text: 'monorepo', link: 'Pnpm/monorepo' },
      { text: 'node-modules', link: 'Pnpm/node-modules' },
      { text: 'note', link: 'Pnpm/note' },
      { text: 'store', link: 'Pnpm/store' },
    ],
  },
  {
    text: 'Tailwind CSS',
    collapsed: true,
    items: [
      { text: 'use-with-ui-library', link: 'Tailwind CSS/use-with-ui-library' },
      { text: '任意值', link: 'Tailwind CSS/任意值' },
      { text: '使用方式', link: 'Tailwind CSS/使用方式' },
    ],
  },
  {
    text: 'TypeScript',
    collapsed: true,
    items: [
      {
        text: 'config',
        collapsed: true,
        items: [
          { text: 'baseurl-paths', link: 'TypeScript/config/baseurl-paths' },
          { text: 'basic', link: 'TypeScript/config/basic' },
          { text: 'esmoduleInterop-importhelpers', link: 'TypeScript/config/esmoduleInterop-importhelpers' },
          { text: 'files-extends-include-exclude', link: 'TypeScript/config/files-extends-include-exclude' },
          { text: 'isolatedmodules', link: 'TypeScript/config/isolatedmodules' },
          { text: 'jsx', link: 'TypeScript/config/jsx' },
          { text: 'lib', link: 'TypeScript/config/lib' },
          { text: 'moduleresolution', link: 'TypeScript/config/moduleresolution' },
          { text: 'nounusedlocals-nounusedparameters', link: 'TypeScript/config/nounusedlocals-nounusedparameters' },
          { text: 'paths', link: 'TypeScript/config/paths' },
          { text: 'references-composite', link: 'TypeScript/config/references-composite' },
          { text: 'rootdir-out-outdir-outfile', link: 'TypeScript/config/rootdir-out-outdir-outfile' },
          { text: 'strict', link: 'TypeScript/config/strict' },
          { text: 'target-module', link: 'TypeScript/config/target-module' },
          { text: 'target', link: 'TypeScript/config/target' },
          { text: 'types', link: 'TypeScript/config/types' },
        ],
      },
      { text: 'create-union-type-use-array-object', link: 'TypeScript/create-union-type-use-array-object' },
      {
        text: 'declaration',
        collapsed: true,
        items: [
          { text: 'declare-global', link: 'TypeScript/declaration/declare-global' },
          { text: 'declare-module', link: 'TypeScript/declaration/declare-module' },
          { text: 'declare-module1', link: 'TypeScript/declaration/declare-module1' },
          { text: 'declare-module2', link: 'TypeScript/declaration/declare-module2' },
          { text: 'declare', link: 'TypeScript/declaration/declare' },
          { text: 'generate-declaration-file-by-ts', link: 'TypeScript/declaration/generate-declaration-file-by-ts' },
          { text: 'use-a-dependency-without-declaration-file', link: 'TypeScript/declaration/use-a-dependency-without-declaration-file' },
        ],
      },
      { text: 'declaration-spaces', link: 'TypeScript/declaration-spaces' },
      { text: 'extends', link: 'TypeScript/extends' },
      { text: 'global-file-module', link: 'TypeScript/global-file-module' },
      { text: 'import-require-for-importing-type-only', link: 'TypeScript/import-require-for-importing-type-only' },
      { text: 'integrate-eslint', link: 'TypeScript/integrate-eslint' },
      { text: 'literal-inference', link: 'TypeScript/literal-inference' },
      { text: 'module', link: 'TypeScript/module' },
      { text: 'namespace', link: 'TypeScript/namespace' },
      { text: 'note', link: 'TypeScript/note' },
      { text: 'symbol', link: 'TypeScript/symbol' },
      { text: 'type-alias-vs-interface', link: 'TypeScript/type-alias-vs-interface' },
      { text: 'type-annotation-inference-assertion', link: 'TypeScript/type-annotation-inference-assertion' },
      { text: 'type-manipulation', link: 'TypeScript/type-manipulation' },
      { text: 'type-predicates', link: 'TypeScript/type-predicates' },
      { text: 'utility-types', link: 'TypeScript/utility-types' },
    ],
  },
]
