import type { DefaultTheme } from 'vitepress'

export const basicSidebar: DefaultTheme.SidebarItem[] = [
  {
    text: 'HTML',
    collapsed: false,
    items: [
      { text: 'contenteditable', link: '/HTML/contenteditable' },
      {
        text: 'svg',
        collapsed: true,
        items: [
          { text: 'basic', link: '/HTML/svg/basic' },
          { text: 'element', link: '/HTML/svg/element' },
          { text: 'fill-stroke', link: '/HTML/svg/fill-stroke' },
          { text: 'svg-sprite', link: '/HTML/svg/svg-sprite' },
          { text: 'viewbox', link: '/HTML/svg/viewbox' },
        ],
      },
      { text: '使用 Preload、Prefetch 优化前端页面的资源加载', link: '/HTML/使用 Preload、Prefetch 优化前端页面的资源加载' },
      { text: '字符实体', link: '/HTML/字符实体' },
      { text: '拖放', link: '/HTML/拖放' },
    ],
  },
  {
    text: 'CSS',
    collapsed: true,
    items: [
      { text: 'currentColor', link: '/CSS/currentColor' },
      { text: 'filter', link: '/CSS/filter' },
      {
        text: 'flex',
        collapsed: true,
        items: [
          { text: 'basic', link: '/CSS/flex/basic' },
          { text: 'flex-basis', link: '/CSS/flex/flex-basis' },
          { text: 'flex-wrap-vs-flex-shrink', link: '/CSS/flex/flex-wrap-vs-flex-shrink' },
          { text: 'shorthand-values-for-the-flex-properties', link: '/CSS/flex/shorthand-values-for-the-flex-properties' },
        ],
      },
      { text: '修改滚动条样式', link: '/CSS/修改滚动条样式' },
      { text: '背景', link: '/CSS/背景' },
    ],
  },
  {
    text: 'JS',
    collapsed: true,
    items: [
      {
        text: 'blob',
        collapsed: true,
        items: [
          { text: 'arraybuffer', link: '/JS/blob/arraybuffer' },
          { text: 'blob-url-vs-data-url', link: '/JS/blob/blob-url-vs-data-url' },
          { text: 'download-by-api', link: '/JS/blob/download-by-api' },
          { text: 'formdata', link: '/JS/blob/formdata' },
          { text: 'use-file', link: '/JS/blob/use-file' },
        ],
      },
      { text: 'break、continue', link: '/JS/break、continue' },
      { text: 'call、apply、bind', link: '/JS/call、apply、bind' },
      { text: 'decodeURI、decodeURIComponent', link: '/JS/decodeURI、decodeURIComponent' },
      { text: 'ECMAScript', link: '/JS/ECMAScript' },
      { text: 'for 循环', link: '/JS/for 循环' },
      {
        text: 'HTTP',
        collapsed: true,
        items: [
          { text: 'Content-Type', link: '/JS/HTTP/Content-Type' },
          { text: 'OPTIONS 请求方法', link: '/JS/HTTP/OPTIONS 请求方法' },
          { text: '传统项目解决跨域问题', link: '/JS/HTTP/传统项目解决跨域问题' },
          { text: '浏览器缓存机制', link: '/JS/HTTP/浏览器缓存机制' },
        ],
      },
      { text: 'JSON.stringify', link: '/JS/JSON.stringify' },
      { text: 'Math', link: '/JS/Math' },
      { text: 'mouseover、mouseenter', link: '/JS/mouseover、mouseenter' },
      { text: 'Number、parseInt、parseFloat', link: '/JS/Number、parseInt、parseFloat' },
      { text: 'Object.keys()的顺序问题及参数解析', link: '/JS/Object.keys()的顺序问题及参数解析' },
      { text: 'UrlEncode 编码', link: '/JS/UrlEncode 编码' },
      {
        text: '下载',
        collapsed: true,
        items: [
          { text: 'basic', link: '/JS/下载/basic' },
        ],
      },
      {
        text: '事件',
        collapsed: true,
        items: [
          { text: 'capture-bubble', link: '/JS/事件/capture-bubble' },
          { text: 'event-loop', link: '/JS/事件/event-loop' },
          { text: 'evnet-call', link: '/JS/事件/evnet-call' },
          { text: 'input-change', link: '/JS/事件/input-change' },
        ],
      },
      {
        text: '位置',
        collapsed: true,
        items: [
          { text: 'pagex-pagey', link: '/JS/位置/pagex-pagey' },
          { text: 'screenx-screeny', link: '/JS/位置/screenx-screeny' },
        ],
      },
      { text: '修改页面内容', link: '/JS/修改页面内容' },
      {
        text: '函数',
        collapsed: true,
        items: [
          { text: 'anonymous-function', link: '/JS/函数/anonymous-function' },
          { text: 'iife', link: '/JS/函数/iife' },
        ],
      },
      { text: '各种符号', link: '/JS/各种符号' },
      { text: '图片', link: '/JS/图片' },
      {
        text: '尺寸',
        collapsed: true,
        items: [
          { text: 'clientheight-scrolltop-scrollheight', link: '/JS/尺寸/clientheight-scrolltop-scrollheight' },
          { text: 'get-width-height', link: '/JS/尺寸/get-width-height' },
          { text: 'getBoundingClientRect', link: '/JS/尺寸/getBoundingClientRect' },
          { text: 'menu-navigation', link: '/JS/尺寸/menu-navigation' },
          { text: 'offset', link: '/JS/尺寸/offset' },
        ],
      },
      { text: '换行', link: '/JS/换行' },
      {
        text: '时间',
        collapsed: true,
        items: [
          { text: 'compatibility', link: '/JS/时间/compatibility' },
          { text: 'data-get-set', link: '/JS/时间/data-get-set' },
          { text: 'timestamp', link: '/JS/时间/timestamp' },
        ],
      },
      {
        text: '模块',
        collapsed: true,
        items: [
          { text: 'apply-module-in-html', link: '/JS/模块/apply-module-in-html' },
          { text: 'import-export', link: '/JS/模块/import-export' },
          { text: 'top-level-await', link: '/JS/模块/top-level-await' },
        ],
      },
      {
        text: '模块化',
        collapsed: true,
        items: [
          { text: 'amd', link: '/JS/模块化/amd' },
          { text: 'cmd', link: '/JS/模块化/cmd' },
          { text: 'commonjs', link: '/JS/模块化/commonjs' },
          { text: 'esm', link: '/JS/模块化/esm' },
          { text: 'umd', link: '/JS/模块化/umd' },
        ],
      },
      {
        text: '正则',
        collapsed: true,
        items: [
          { text: 'basic', link: '/JS/正则/basic' },
          { text: 'match', link: '/JS/正则/match' },
          { text: 'replace', link: '/JS/正则/replace' },
        ],
      },
      {
        text: '类',
        collapsed: true,
        items: [
          { text: 'constructor', link: '/JS/类/constructor' },
          { text: 'this', link: '/JS/类/this' },
        ],
      },
      { text: '类数组', link: '/JS/类数组' },
      { text: '继承与原型链', link: '/JS/继承与原型链' },
      { text: '递归', link: '/JS/递归' },
      { text: '遍历数组删除指定元素', link: '/JS/遍历数组删除指定元素' },
      { text: '闭包', link: '/JS/闭包' },
      { text: '防抖、节流', link: '/JS/防抖、节流' },
    ],
  },
  {
    text: 'NodeJS',
    collapsed: true,
    items: [
      { text: 'argv', link: '/NodeJS/argv' },
      { text: 'dirname', link: '/NodeJS/dirname' },
      { text: 'env', link: '/NodeJS/env' },
      { text: 'file-upload', link: '/NodeJS/file-upload' },
      { text: 'glob', link: '/NodeJS/glob' },
      { text: 'goodPackage', link: '/NodeJS/goodPackage' },
      { text: 'nvm', link: '/NodeJS/nvm' },
    ],
  },
  {
    text: 'NPM',
    collapsed: true,
    items: [
      { text: 'cli', link: '/NPM/cli' },
      { text: 'cli01', link: '/NPM/cli01' },
      { text: 'dependencies-vs-devdependencies', link: '/NPM/dependencies-vs-devdependencies' },
      { text: 'install', link: '/NPM/install' },
      { text: 'install01', link: '/NPM/install01' },
      { text: 'integrity', link: '/NPM/integrity' },
      { text: 'npm-link', link: '/NPM/npm-link' },
      { text: 'npm-mechanism', link: '/NPM/npm-mechanism' },
      { text: 'npx', link: '/NPM/npx' },
      { text: 'nvm-windows', link: '/NPM/nvm-windows' },
      {
        text: 'package',
        collapsed: true,
        items: [
          { text: 'module', link: '/NPM/package/module' },
          { text: 'peerdependencies', link: '/NPM/package/peerdependencies' },
          { text: 'type', link: '/NPM/package/type' },
          { text: 'types', link: '/NPM/package/types' },
          { text: 'unpkg', link: '/NPM/package/unpkg' },
        ],
      },
      { text: 'package-lock', link: '/NPM/package-lock' },
      { text: 'publish-package', link: '/NPM/publish-package' },
      { text: 'scripts-prepend-node-path', link: '/NPM/scripts-prepend-node-path' },
      { text: 'write-package-use-rollup', link: '/NPM/write-package-use-rollup' },
    ],
  },
  {
    text: 'Pnpm',
    collapsed: true,
    items: [
      { text: 'config', link: '/Pnpm/config' },
      { text: 'install', link: '/Pnpm/install' },
      { text: 'monorepo', link: '/Pnpm/monorepo' },
      { text: 'node-modules', link: '/Pnpm/node-modules' },
      { text: 'note', link: '/Pnpm/note' },
      { text: 'store', link: '/Pnpm/store' },
    ],
  },
  {
    text: 'Tailwind CSS',
    collapsed: true,
    items: [
      { text: 'use-with-ui-library', link: '/Tailwind CSS/use-with-ui-library' },
      { text: '任意值', link: '/Tailwind CSS/任意值' },
      { text: '使用方式', link: '/Tailwind CSS/使用方式' },
    ],
  },
  {
    text: 'TypeScript',
    collapsed: true,
    items: [
      {
        text: 'config',
        collapsed: true,
        items: [
          { text: 'baseurl-paths', link: '/TypeScript/config/baseurl-paths' },
          { text: 'basic', link: '/TypeScript/config/basic' },
          { text: 'esmoduleInterop-importhelpers', link: '/TypeScript/config/esmoduleInterop-importhelpers' },
          { text: 'files-extends-include-exclude', link: '/TypeScript/config/files-extends-include-exclude' },
          { text: 'isolatedmodules', link: '/TypeScript/config/isolatedmodules' },
          { text: 'jsx', link: '/TypeScript/config/jsx' },
          { text: 'lib', link: '/TypeScript/config/lib' },
          { text: 'moduleresolution', link: '/TypeScript/config/moduleresolution' },
          { text: 'nounusedlocals-nounusedparameters', link: '/TypeScript/config/nounusedlocals-nounusedparameters' },
          { text: 'paths', link: '/TypeScript/config/paths' },
          { text: 'references-composite', link: '/TypeScript/config/references-composite' },
          { text: 'rootdir-out-outdir-outfile', link: '/TypeScript/config/rootdir-out-outdir-outfile' },
          { text: 'strict', link: '/TypeScript/config/strict' },
          { text: 'target-module', link: '/TypeScript/config/target-module' },
          { text: 'target', link: '/TypeScript/config/target' },
          { text: 'types', link: '/TypeScript/config/types' },
        ],
      },
      { text: 'create-union-type-use-array-object', link: '/TypeScript/create-union-type-use-array-object' },
      {
        text: 'declaration',
        collapsed: true,
        items: [
          { text: 'declare-global', link: '/TypeScript/declaration/declare-global' },
          { text: 'declare-module', link: '/TypeScript/declaration/declare-module' },
          { text: 'declare-module1', link: '/TypeScript/declaration/declare-module1' },
          { text: 'declare-module2', link: '/TypeScript/declaration/declare-module2' },
          { text: 'declare', link: '/TypeScript/declaration/declare' },
          { text: 'generate-declaration-file-by-ts', link: '/TypeScript/declaration/generate-declaration-file-by-ts' },
          { text: 'use-a-dependency-without-declaration-file', link: '/TypeScript/declaration/use-a-dependency-without-declaration-file' },
        ],
      },
      { text: 'declaration-spaces', link: '/TypeScript/declaration-spaces' },
      { text: 'extends', link: '/TypeScript/extends' },
      { text: 'global-file-module', link: '/TypeScript/global-file-module' },
      { text: 'import-require-for-importing-type-only', link: '/TypeScript/import-require-for-importing-type-only' },
      { text: 'integrate-eslint', link: '/TypeScript/integrate-eslint' },
      { text: 'literal-inference', link: '/TypeScript/literal-inference' },
      { text: 'module', link: '/TypeScript/module' },
      { text: 'namespace', link: '/TypeScript/namespace' },
      { text: 'note', link: '/TypeScript/note' },
      { text: 'symbol', link: '/TypeScript/symbol' },
      { text: 'type-alias-vs-interface', link: '/TypeScript/type-alias-vs-interface' },
      { text: 'type-annotation-inference-assertion', link: '/TypeScript/type-annotation-inference-assertion' },
      { text: 'type-manipulation', link: '/TypeScript/type-manipulation' },
      { text: 'type-predicates', link: '/TypeScript/type-predicates' },
      { text: 'utility-types', link: '/TypeScript/utility-types' },
    ],
  },
]
